### ISSUE TITLE
Reunião - nº: 1 -15:00 - Discord

### ISSUE THREAD

**Issue by max10rogerio** [DOAI-ORG/doai-web-app#1]
Reunião pelo discord para vermos:
- O que temos;
- O que vamos fazer;
- O papel de cada um;

**Sugestão**: Domingo - 16:00 - Via discord ou zoom

> Obs: Escreva abaixo se concorda ou não com a sugestão... Se não concorda justifique ou diga uma nova data.

**Comment by brunosousadev** [comment]
Concordo !

**Comment by humbertoromanojr** [comment]
Concordo e espero por todos , para agente definir e evoluir a aplicação tanto backend, web e mobile

**Comment by max10rogerio** [comment]
Eu esqueci q tinha compromisso as 16:30 neste dia
Vamos fazer às 15:00

**Comment by max10rogerio** [comment]
Na primeira reunião compareceu apenas eu e o @humbertoromanojr...
Decidimos remover todos que não interagem, do grupo do whatsapp

Ficarei com a parte do backend juntamente com o Filipe Calvacante

O junior irá ficar responsável pelo web juntamente com mais 2 pessoas

O mobile ficará para depois de termos um MVP.
