### ISSUE TITLE
[INFO]: Sobre o Projeto

### ISSUE THREAD

**Issue by max10rogerio** [DOAI-ORG/doai-web-app#2]
Gostaria de saber como vocês quais funcionalidade irá ter e a forma que irá funcionar..
Pois percebi que a ideia diverge muito de um para outro...

Na minha concepção está da seguinte forma:

1 - Me cadastro no app;
2 - Tenho uma bicicleta e quero doa-la;
3 - Anuncio que tenho este item para doar no app;
4 - Outra pessoa visualiza meu item e tem interesse;
5 - Conversa comigo e marca de vir buscar;
6 - A pessoa pega o item e marca no aplicativo que não está mais disponível;

__Essa pra mim ia ser a base__

E para vocês que tipo de funcionamento pensaram para o app?

**Comment by adailsonaguiar** [comment]
Na minha concepção a aplicação seria voltada para organizações de apoio aos necessitados ( onde se concentram mais pessoas que realmente precisam de algo).
- A organização é cadastrada na plataforma e anuncia o que precisa receber. 
- As pessoas veem no mapa ia locais de doação e quais os produtos que se pedem.

**Comment by humbertoromanojr** [comment]
Na minha opinião eu pensei que a priore o App era para cadastrar locais onde as pessoas iriam doar cestas básicas, alimentos para as famílias com necessidades.

- A organização e cadastrada e la teria quer ter a quantidade mínima de doação atingida na semana;
- E as pessoas verem no App e irem doar para ajudar as famílias da região;  

**só para registrar umas dicas importantes**
- no cadastro das instituições, seria legal elas cadastrarem as urgências, podemos criar um Select de categorias como por exemplo: - Alimentos, - farmácia , - Objetos, etc

assim os doares da região já podem ajudar o que e de muito urgência.

**Comment by FilipeHub** [comment]
Meu entendimento é parecido com o de Adailson:

O app seria voltada para organizações como asilos, orfanatos, etc.

A organização é cadastrada na plataforma e anuncia o que precisa receber.
As pessoas veem no mapa ia locais de doação e quais os produtos que se pedem.

**Comment by max10rogerio** [comment]
Eu achei bacana as idéias...
Mas também acho que o app somente fazer uma coisa não seria eficiente...
O que acham de o app permitir:

- Adicionar instituição de caridade (casa de repouso de idosos, centro de adoção de animais)
- Adicionar pessoa necessitada (que precisa de um colchão, cesta básica e etc...)
- Ter algo como o `bom samaritano do mês`, onde mostraríamos a pessoa que mais contribuiu no período de um mês
- Ter a possibilidade de cadastrar preferências, ex: 
    - sou doador e adiciona a preferência para doar para centro de adoção de animais
    - um centro de adoção de animais adicionou que precisa urgente de 100 kilos de ração para gato
    - o app me notificar que o lugar está precisando de ração
- Também mostrar a porcentagem da meta, citando o exemplo acima... foi doado 50 kilos de ração e meta aparecer em 50%
- Também ter a possibilidade de cadastrar eventos (aqui na minha cidade tem a adoção de cachorros aos domingos em uma praça no centro)
- Ter possibilidade de vincular redes sociais: Facebook, Instagram, Twitter

**Comment by max10rogerio** [comment]
Como essas ideias podemos já polir a regra de negócio

**Comment by humbertoromanojr** [comment]
Pessoal um detalhe importante agora que temos que conversar, e sobre a estrutura padrão de projeto. Estou fazendo da seguinte forma :

- src/components/Header
index.tsx e styles.js 
- src/pages/Dashboard/
index.tsx e styles.js 

o que vocês acham ?

**Comment by elascalla** [comment]
O meu entendimento é igual ao do @adailsonaguiar também. Acredito que o app deve ser focado na organização que queira receber a doação. Existem muitas pessoas que querem doar, mas não sabem onde doar, tendo um aplicativo/web que mostre para ela locais próximos e suas necessidades seria perfeito.

Acredito que inicialmente o sistema deva resolver essas questões básicas primeiramente.

**Comment by max10rogerio** [comment]
Ok. Focaremos em desenvolver algo para localizar as  organizações

**Comment by max10rogerio** [comment]
Sobre a pergunta do humberto criei uma nova issue.

[PATTERNS](https://github.com/doiaidev/doai-web-app/issues/2)
