### ISSUE TITLE
[Tópico] Patterns

### ISSUE THREAD

**Issue by max10rogerio** [DOAI-ORG/doai-web-app#3]
@humbertoromanojr 

Abri essa issue sobre a pergunta do humberto na [**ISSUE 2**](https://github.com/doiaidev/doai-web-app/issues/2#issuecomment-581047034)

*Pessoal um detalhe importante agora que temos que conversar, e sobre a estrutura padrão de projeto. Estou fazendo da seguinte forma:*
```js
src/components/Header
index.tsx e styles.js
src/pages/Dashboard/
index.tsx e styles.js
```
*o que vocês acham ?*

**Comment by max10rogerio** [comment]
eu prefiro seguir umas dicas dessa doc: https://basarat.gitbook.io/typescript/
Basicamente gosto da seguinte estrutura:

```fs
/assets
  /images
  /themes
/components
  /MyComponent
    index.ts
    MyComponent.tsx
/hooks
/pages
  /_layouts // layouts que serão padrões de tela (se houver necessidade)
    /Main
      index.ts
      Main.tsx
  /MyPage01
    /components // se a pagina tiver q ser quebrada em mais componentes
      FormPage01.tsx 
    index.ts
    MyPage01.tsx
/routes // Config de rodas e afins
/services // chamadas a api, instancias do axios
/utils // funções q sempre serão reutilizadas
```

*Por que sempre tem não fazer tudo em um arquivo `index.tsx` direto?*

Segundo a TypeScript Deep Dive (https://basarat.gitbook.io/typescript/main-1/defaultisbad), o intellisense do vscode funciona melhor quando não se tem `export default` e também não gosto de na aba do vscode todos os arquivos fiquem com o nome de index.tsx
![image](https://user-images.githubusercontent.com/21085292/73649257-292e6d00-465e-11ea-8a9c-364e32de7153.png)

Acho assim mais bonito e legível para desenvolvermos:
![image](https://user-images.githubusercontent.com/21085292/73649317-4cf1b300-465e-11ea-8edd-22a730d4d706.png)

o arquivo `index.ts` teria apenas os exports:
```ts
export * from './MyComponent'

// e quando for usar
import { MyComponent } from './MyComponent' 

```

**Comment by adailsonaguiar** [comment]
@max10rogerio perfeito!

**Comment by humbertoromanojr** [comment]
apenas escrevendo para registrar, antes que eu esqueça e também ficando todos cientes. 
Antes de upar o projeto para produção, temos que rever todas as imagens e seus direitos autorais.
